# Written by e2xray after a VLESS link is saved.
SERVER_ADDRESS=""
SERVER_PORT="443"
UUID=""
SNI=""
PUBLIC_KEY=""
SHORT_ID=""
FINGERPRINT="chrome"
SECURITY="reality"
NETWORK="tcp"
TRANSPORT_PATH=""
HOST=""
FLOW=""
